=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio_8/ej9/exercici9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <xs:element name="partit">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="equips">
          <xs:complexType>
         <xs:sequence>
          <xs:element name="local">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element name="gols"   maxOccurs="unbounded">
                  <xs:complexType >
                  <xs:sequence>
                    <xs:element name="jugador" type="xs:string" minOccurs="0"/>
                    <xs:element name="minut" type="xs:integer" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
                </xs:element>
                <xs:element name="targetes" minOccurs="0">
                  <xs:complexType>
              <xs:sequence>
                <xs:element name="tgrogues" minOccurs="0"  maxOccurs="unbounded">
                  <xs:complexType >
                  <xs:sequence>
                    <xs:element name="jugador" type="xs:string"/>
                    <xs:element name="minut" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
                </xs:element>
                <xs:element name="tvermelles" minOccurs="0"  maxOccurs="unbounded">
                  <xs:complexType >
                  <xs:sequence>
                    <xs:element name="jugador" type="xs:string"/>
                    <xs:element name="minut" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
              </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="visitant">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element name="gols"   maxOccurs="unbounded">
                  <xs:complexType >
                  <xs:sequence>
                    <xs:element name="jugador" type="xs:string" minOccurs="0"/>
                    <xs:element name="minut" type="xs:integer" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
                </xs:element>
                <xs:element name="targetes" minOccurs="0">
                  <xs:complexType>
              <xs:sequence>
                <xs:element name="tgrogues" minOccurs="0"  maxOccurs="unbounded">
                  <xs:complexType >
                  <xs:sequence>
                    <xs:element name="jugador" type="xs:string" />
                    <xs:element name="minut" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
                </xs:element>
                <xs:element name="tvermelles" minOccurs="0">
                  <xs:complexType >
                  <xs:sequence>
                    <xs:element name="jugador" type="xs:string"/>
                    <xs:element name="minut" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
              </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:complexType>

        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>



</xs:schema>

=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio_8/ej8/exercici8.xml
<?xml version="1.0" encoding="UTF-8"?>
<partit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../ej9/exercici9.xsd">
  <equips>
    <local>
      <nom>Barcelona</nom>
      <gols>
        <jugador>Messi</jugador>
        <minut>10</minut>
      </gols>
      <gols>
        <jugador>Villa</jugador>
        <minut>80</minut>
      </gols>
      <targetes>
      <tgrogues>
        <jugador>Pique</jugador>
        <minut>30</minut>
      </tgrogues>
      <tgrogues>
        <jugador>Alba</jugador>
        <minut>75</minut>
      </tgrogues>
    </targetes>
    </local>
    <visitant>
      <nom>Real Madrid</nom>
      <gols>
        <jugador>Cristiano</jugador>
        <minut>20</minut>
      </gols>
      <gols>
        <jugador>Benzema</jugador>
        <minut>88</minut>
      </gols>
      <gols>
        <jugador>Ramos</jugador>
        <minut>90</minut>
      </gols>
      <targetes>
      <tgrogues>
        <jugador>Ramos</jugador>
        <minut>30</minut>
        </tgrogues>
        <tvermelles>
        <jugador>Pepe</jugador>
        <minut>79</minut>
      </tvermelles>
    </targetes>
    </visitant>
  </equips>

</partit>
