=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio_8/ej7/exercici7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="carta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="benvinguda">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="tracte" type="xs:string"/>
                            <xs:element name="nom" type="xs:string"/>
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
                <xs:element name="cos" type="xs:string"/>
                <xs:element name="signatura" type="xs:string"/>
                <xs:element name="data">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="mes" type="xs:string"/>
                            <xs:element name="any" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio_8/ej7/exercici7.xml
<?xml version="1.0" ?>
<carta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./exercici7.xsd">
    <benvinguda>Apreciat<tracte>Sr/a.</tracte><nom>Bruno</nom></benvinguda>
    <cos>Ens dirigim a vost√® per ...</cos>
    <signatura>Atentament ...</signatura>
    <data>15 de <mes>novembre</mes> del <any>2018</any></data>
</carta>
