=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/exercici6/personal/personal.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT personal (persona)+>
<!ELEMENT persona (dades,email*,url*,relaci贸?)>
<!ATTLIST persona id ID #REQUIRED>
<!ATTLIST persona note CDATA #IMPLIED>
<!ATTLIST persona contr (true|false) >
<!ATTLIST persona salary CDATA #IMPLIED>
<!ELEMENT dades ((cognom,nom)|(nom,cognom))>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url EMPTY>
<!ATTLIST url href CDATA 'http://'>
<!ELEMENT relaci贸 EMPTY>
<!ATTLIST relaci贸 director IDREF #IMPLIED>
<!ATTLIST relaci贸 treballador IDREFS #IMPLIED>

=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/exercici6/personal/personal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personal SYSTEM "personal.dtd">
<personal>
    <persona id="bruno" note="alumno" contr="true" salary="1000">
        <dades>
            <nom>Bruno</nom> 
            <cognom>Ostos</cognom>
        </dades>
        <email>bostos@insdanielblanxart.cat</email>
        <url href='http://'>iyreu</url>
        <relaci贸 ></relaci贸>
    </persona>
    <persona id="jose" note="alumno" contr="true" salary="1000">
        <dades>
            <cognom>Turrado</cognom>
            <nom>Jose</nom>
        </dades>
        <email>jturrado@insdanielblanxart.cat</email>
        <url href='http://'></url>
        <relaci贸 ></relaci贸>
    </persona>
</personal>
