=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio5/ejercicio4.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT missatges (missatge)>
<!ELEMENT de (#PCDATA)>
<!ELEMENT per (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio5/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE missatges SYSTEM "ejercicio4.dtd">
<missatges>
    <missatge>
        <de>Pepe (pepe@insdanielblanxart.cat)</de>
        <per>Juan (juan@insdanielblanxart.cat)</per>
        <hora>28/02/2011 17:48:23,61</hora>
        <text>¿Hola, Juan, qué haces?</text>
    </missatge>
    <missatge>
        <de>Juan (juan@insdanielblanxart.cat)</de>
        <per>Pepe (pepe@insdanielblanxart.cat)</per>
        <hora>28/02/2011 17:54:20,87</hora>
        <text>Aquí, aprendiendo <strong>XML</strong></text>
    </missatge>
</missatges>
