=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio5/ejercicio1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT matricula (cicle,alumnes)+>
<!ELEMENT cicle (#PCDATA)>
<!ELEMENT alumnes (alumne)>
<!ELEMENT alumne (nom,any,moduls)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT moduls (modul+)>
<!ELEMENT modul (#PCDATA)>

=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio5/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula SYSTEM "ejercicio1.dtd">
<matricula>
    <cicle> Administració de sistemes informàtics i xarxes</cicle>
    <alumnes>
        <alumne>
        <nom>Federicu Pi</nom>
        <any>2010</any>
        <moduls>
            <modul>XML</modul>
            <modul>Xarxes Locals</modul>
        </moduls>
        </alumne>
    </alumnes>
</matricula>
