=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio5/exercici3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT artistes (artista)>
<!ELEMENT artista (nom,sobrenom,dataNaixament) >
<!ELEMENT nom (#PCDATA)>
<!ELEMENT sobrenom (#PCDATA)>
<!ELEMENT dataNaixement (#PCDATA)>

=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio5/exercici3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE artistes SYSTEM "exercici3.dtd">
<artistes>
    <artista>
        <nom>Salvador Dalí</nom>
        <sobrenom>El geni de Figueres</sobrenom>
        <dataNaixement>11 de maig de 1904</dataNaixement>
    </artista>
    <artista>
        <nom>Pablo Ruíz Picasso</nom>
        <sobrenom>Picasso</sobrenom>
        <dataNaixement>25 d’octubre de 1881</dataNaixement>
    </artista>
</artistes>
