=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio_8/ej4/guia_telefonica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="guia_telefonica">
    <xs:complexType>
      <xs:sequence>
      <xs:element name="telefons" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="nom" maxOccurs="unbounded"/>
            <xs:element name="cognom" maxOccurs="unbounded"/>
            <xs:element name="telefon" type="telefono"/>
        </xs:sequence>
      </xs:complexType>
      </xs:element>
    </xs:sequence>
    </xs:complexType>
  
</xs:element>
        <xs:simpleType name="telefono">
            <xs:restriction base="xs:string">
              <xs:pattern value="\+[0-9]{3}[0-9]{7}"/>
              <xs:pattern value="\+[0-9]{4}[0-9]{7}"/>
            </xs:restriction>
          </xs:simpleType>
</xs:schema>

=== Ruuculaa/portafolios-andreagarreta/curs 2/mp04/uf1/ejercicio_8/ej4/guia_telefonica.xml
<?xml version="1.0" encoding="UTF-8"?>
<guia_telefonica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="guia_telefonica.xsd">
<telefons>
    <nom>Raul</nom>
    <cognom>Masso</cognom>
    <telefon>+3468404256</telefon>
</telefons>
<telefons>
    <nom>Manuel</nom>
    <cognom>Masso</cognom>
    <telefon>+3468404256</telefon>
</telefons>
</guia_telefonica>
